// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace com.example
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class ExtraOrdinaryPerson : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"ExtraOrdinaryPerson\",\"namespace\":\"com.example\",\"fields\":" +
				"[{\"name\":\"Id\",\"type\":\"int\"},{\"name\":\"Name\",\"type\":\"string\"},{\"name\":\"Age\",\"type\"" +
				":\"int\"},{\"name\":\"Email\",\"type\":\"string\"},{\"name\":\"Address\",\"type\":\"string\"}]}");
		private int _Id;
		private string _Name;
		private int _Age;
		private string _Email;
		private string _Address;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return ExtraOrdinaryPerson._SCHEMA;
			}
		}
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public int Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				this._Age = value;
			}
		}
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				this._Email = value;
			}
		}
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				this._Address = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.Name;
			case 2: return this.Age;
			case 3: return this.Email;
			case 4: return this.Address;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Int32)fieldValue; break;
			case 1: this.Name = (System.String)fieldValue; break;
			case 2: this.Age = (System.Int32)fieldValue; break;
			case 3: this.Email = (System.String)fieldValue; break;
			case 4: this.Address = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
